name: fair_bandits
channels:
  - javascript
dependencies:
  - pytorch=1.7
  - python=3.7  
  - matplotlib
  - pandas
  - scipy
  - sklearn
  - torchvision
  - IPython
  - pip:
    - ray
    - sklearn
